### ISSUE TITLE
Client mods list are outdated

### ISSUE THREAD

**Issue by DodoGames7** [jacc/awesome-discord#106]
The Client mods list on readme are pretty old compared to what is currently updated nowadays:

# Missing
* [Vencord](https://github.com/Vendicated/Vencord): The cutest Discord client mod
* [Replugged](https://replugged.dev/): Enhance your Discord experience with new features and looks. Replugged makes your Discord truly _yours_.
* [Vendetta](https://github.com/vendetta-mod/Vendetta/): A mod for Discord's mobile apps.
* [Enmity](https://github.com/enmity-mod/enmity): The power of addons, all in your hand.
* [Shelter](https://github.com/uwu/shelter): _an attempt to prepare for the worst_

# Should be removed
* Powercord: no longer maintained due to it being [EOL](https://github.com/powercord-org/powercord#read-first) as of 2022, Replugged is the new powercord.
* Bluecord: Nothing but apparently seems to be infamous for being [malware](https://drive.google.com/drive/u/0/folders/1Y2m2lMSpN3GlOcXyceaO88Ljnr8xuNcp) (yes this is actually a link to a couple of screenshots of Bluecord's dev doing various malicious stuff)

# Should be edited
* Betterdiscord: uses an outdated link, `betterdiscord.app` is the actual link

**Comment by jacc** [comment]
Feel free to leave a PR! This list hasn't been maintained in a while.

**Comment by DodoGames7** [comment]
Alright, will do when I have time.
