### ISSUE TITLE
Discussion — Should the "Popular Servers" category stay?

### ISSUE THREAD

**Issue by byparallax** [jacc/awesome-discord#15]
Hey there, while browsing a few of the ressources linked inside the repository, I asked myself: "Do we really need a popular servers category?". Of course, that's a pretty random thought but I decided to explore it a little further so I will drop my ideas and concerns bellow: 

1. It's currently only a bunch of reddit-communities servers; making it kinda restricted.
2. There are so many popular servers if we consider "popular" as 5k+ online users that we would need a dedicated repository. 
3. Discord servers are not specifically great resources. On the same thought, some will say that bots should be removed as your tastes might not fit someone's else; but bots can be added to other servers - making them a kind of resources. 

I'll conclude this by saying that having the current "Server Lists" category should cover any user's need if they are looking for servers. What are your thoughts and opinions?

**Comment by jacc** [comment]
Personally I added it for some popular servers that people moght join first. I do understand your point of view though.

**Comment by austinhuang0131** [comment]
Against. An awesome list lists resources. If the user is going to join big servers, they'll eventually find their way.

**Comment by jacc** [comment]
Fair enough. Pulling and closing.
