### ISSUE TITLE
[Discussion] - About the roadmap.

### ISSUE THREAD

**Issue by byparallax** [jacc/awesome-discord#31]
### This thread is related to the [RoadMap](https://github.com/jacc/awesome-discord/projects/1), please consult it before participating. 
-----

**\# Add legend of images.**

I'm not sure to understand this one, could you clarify please?

**\# Add servers list.**

This was rejected in #17 & #15, therefore should be moved to a different list.

**\# Add more official links.**

I can include more official links, if you want me to do so but I believe the current amount is correct. *To be discussed.* 

**\# Create "Back To Top" buttons.**

This was added in #19, therefore should be moved to the "Done" list.

**Comment by jacc** [comment]
### **Legend of images**
https://elon-musk.is-fi.re/2632cc.png
Was hoping to accomplish something like that.

### **Add servers list**
I'll create a category on the roadmap for rejected ideas.

### **Add more official links**
So for this one, I don't really know what other links we could add. What do you have?

## **Create "back to the top" buttoms
Added to done list.

**Comment by byparallax** [comment]
This issue should now be discussed on the official discord server. Closing.
