### ISSUE TITLE
[Discussion] - Add more descriptions for official content.

### ISSUE THREAD

**Issue by byparallax** [jacc/awesome-discord#41]
Since Discord Nitro got updated in #40 with a description, I believe it could great to add one for the other elements of the list. However, it's clearly not required if the entry's name is obvious enough.

**Comment by justdotJS** [comment]
Here are some descriptions which could be added:

Discord Testers - Test, improve, and report Discord bugs.
Discord API - Discussion, support, and more related to Discord's API.
Discord Feedback - Give and vote on feedback about Discord.
Discord Events - News and announcements related to Official Discord Events.
Developer Documentation - Documentation for using Discord's API.
Discord Blog - Discord's Blog, where you can find change logs and more.
Discord Nitro - Support Discord's development and get some sweet perks.
Discord Status - Find out Discord's current status, and any planned maintenance.
HypeSquad - Join the HypeSquad and let Discord support your gaming community.
Partners - Join the Discord fam and get partner-only tools to make you stand out.
Verification - Verify your server so people know where to find their favorite artists, esports organizations, and game studios.


If those seem OK I can create a PR?

**Comment by byparallax** [comment]
That sounds great to me, go ahead.
